local GameMode = GameRules:GetGameModeEntity()

GameMode:SetCameraDistanceOverride(1500)
GameRules:SetCustomGameSetupAutoLaunchDelay(0)
GameRules:SetHeroSelectionTime(0)
GameRules:SetHeroSelectPenaltyTime(0)
GameRules:SetStrategyTime(0)
GameRules:SetShowcaseTime(0)
GameRules:SetPreGameTime(5)
GameRules:SetCustomGameTeamMaxPlayers(DOTA_TEAM_GOODGUYS, 0)
GameRules:SetCustomGameTeamMaxPlayers(DOTA_TEAM_BADGUYS, 0)
GameRules:SetCustomGameTeamMaxPlayers(DOTA_TEAM_CUSTOM_1, 1)
GameRules:SetCustomGameTeamMaxPlayers(DOTA_TEAM_CUSTOM_2, 1)
GameRules:SetCustomGameTeamMaxPlayers(DOTA_TEAM_CUSTOM_3, 1)
GameRules:SetCustomGameTeamMaxPlayers(DOTA_TEAM_CUSTOM_4, 1)
GameRules:SetCustomGameTeamMaxPlayers(DOTA_TEAM_CUSTOM_5, 1)
GameRules:SetCustomGameTeamMaxPlayers(DOTA_TEAM_CUSTOM_6, 1)
GameMode:SetDraftingHeroPickSelectTimeOverride(1)
GameMode:SetFogOfWarDisabled(true)